#include <string.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include "../Defs/defs.hpp"
#include "../Calc/calc.hpp"
#include "../Ranmar/ranmar.hpp"
#include "../Random/random.hpp"
#include "cls.hpp"
